// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pcov_va
double pcov_va(const NumericMatrix& a, const NumericMatrix& b);
RcppExport SEXP _PCOR_pcov_va(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(pcov_va(a, b));
    return rcpp_result_gen;
END_RCPP
}
// pcor_va
double pcor_va(const NumericMatrix& a, const NumericMatrix& b);
RcppExport SEXP _PCOR_pcor_va(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(pcor_va(a, b));
    return rcpp_result_gen;
END_RCPP
}
// t_va
double t_va(const NumericMatrix& a, const NumericMatrix& b);
RcppExport SEXP _PCOR_t_va(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(t_va(a, b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PCOR_pcov_va", (DL_FUNC) &_PCOR_pcov_va, 2},
    {"_PCOR_pcor_va", (DL_FUNC) &_PCOR_pcor_va, 2},
    {"_PCOR_t_va", (DL_FUNC) &_PCOR_t_va, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_PCOR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
