# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pcov_va <- function(a, b) {
    .Call(`_PCOR_pcov_va`, a, b)
}

pcor_va <- function(a, b) {
    .Call(`_PCOR_pcor_va`, a, b)
}

t_va <- function(a, b) {
    .Call(`_PCOR_t_va`, a, b)
}

